const TABLE_SIZE = 'TABLE_SIZE';
const CHANGE_TEXT = 'CHANGE_TEXT';
const APPLY_STYLE = 'APPLY_STYLE';
const CHANGE_STYLES = 'CHANGE_STYLES';

export {TABLE_SIZE, CHANGE_TEXT, APPLY_STYLE, CHANGE_STYLES}